import React from 'react'

const Description = () => {
    return (
        <div className='home-description'>
            <p> Welcome to ENScope, the comprehensive carbon footprint tool for your business! We are committed to helping you understand your carbon footprint and take steps towards reducing your impact on the environment. Our tool is designed to help you record and manage your carbon footprint by calculating Scope 1, Scope 2 and Scope 3 emissions of your business. Our tool strongly adheres with international standards like Greenhouse Gas Protocol and ISO 14064 for assessing carbon footprint of your business. ENScope is designed to help you calculate your business’s carbon footprint by answering a few simple questions and providing data related to your energy consumption, transportation, and more. But our tool doesn’t just stop at providing you with a number. Our tool provides you with detailed reports and insights on your emissions, helping you to identify areas for improvement and set reduction targets. We also provide you with personalized recommendations and tips on how to reduce your carbon footprint. Our team of experts has carefully curated a list of actionable steps you can take to reduce your impact on the environment, whether it’s by changing your operational processes, using energy-efficient products, or investing in renewable energy sources. We understand that reducing your carbon footprint can be overwhelming and confusing. That’s why we’ve made our tool easy to use and understand. Our user-friendly interface and informative explanations make it easy for anyone to use, regardless of their level of environmental knowledge. We also believe that reducing your carbon footprint should be a collective effort. That’s why we encourage you to share our tool with your peer businesses, vendors and suppliers. By working together, we can create a more sustainable future for ourselves and for generations to come. Thank you for choosing ENScope. We look forward to help you take the first step towards reducing your impact on the environment. We are committed to helping you achieve your sustainability goals and to creating a more sustainable future for all.</p>
        </div>
    )
}

export default Description